name: new-version

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      # Check commit, package.json and package-lock.json are all changed
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: npm pack
      # Publish
